import { AppState, Debt, Expense, Product, Settings, Transaction } from "@/lib/types";

function daysAgo(days: number, hour: number, minute = 0) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

const products: Product[] = [
  // ── Makanan ──────────────────────────────────────────────────
  {
    id: "prd_nasi_goreng",
    name: "Nasi Goreng Spesial",
    category: "Makanan",
    buyPrice: 7000,
    sellPrice: 12000,
    stock: 30,
    minimumStock: 5,
    description: "Nasi goreng dengan telur, ayam suwir, dan kerupuk. Favorit pelanggan!",
  },
  {
    id: "prd_mie_goreng",
    name: "Mie Goreng",
    category: "Makanan",
    buyPrice: 6000,
    sellPrice: 10000,
    stock: 25,
    minimumStock: 5,
    description: "Mie goreng gurih dengan sayuran dan bumbu rahasia dapur Nona Suka.",
  },
  {
    id: "prd_nasi_ayam",
    name: "Nasi Ayam Penyet",
    category: "Makanan",
    buyPrice: 9000,
    sellPrice: 15000,
    stock: 20,
    minimumStock: 5,
    description: "Ayam goreng penyet sambal, nasi putih, lalapan segar.",
  },
  {
    id: "prd_roti_bakar",
    name: "Roti Bakar Coklat Keju",
    category: "Makanan",
    buyPrice: 5000,
    sellPrice: 8000,
    stock: 20,
    minimumStock: 6,
    description: "Roti bakar garing isi coklat meses dan keju leleh. Cocok untuk sarapan.",
  },
  {
    id: "prd_pisang_goreng",
    name: "Pisang Goreng (3 pcs)",
    category: "Makanan",
    buyPrice: 3000,
    sellPrice: 5000,
    stock: 15,
    minimumStock: 5,
    description: "Pisang kepok goreng renyah, cocok untuk camilan sore.",
  },
  {
    id: "prd_gorengan",
    name: "Gorengan Aneka (5 pcs)",
    category: "Makanan",
    buyPrice: 3000,
    sellPrice: 5000,
    stock: 20,
    minimumStock: 5,
    description: "Tempe, tahu, bakwan, dan ote-ote goreng crispy.",
  },
  {
    id: "prd_nasi_kuning",
    name: "Nasi Kuning",
    category: "Makanan",
    buyPrice: 5000,
    sellPrice: 8000,
    stock: 15,
    minimumStock: 4,
    description: "Nasi kuning lengkap dengan serundeng, telur, dan lauk pilihan.",
  },
  {
    id: "prd_indomie",
    name: "Indomie Goreng",
    category: "Makanan",
    buyPrice: 3500,
    sellPrice: 6000,
    stock: 40,
    minimumStock: 10,
    description: "Indomie goreng rebus dengan tambahan telur ceplok dan kerupuk.",
  },

  // ── Jus Segar ─────────────────────────────────────────────────
  {
    id: "prd_jus_alpukat",
    name: "Jus Alpukat",
    category: "Jus Segar",
    buyPrice: 5500,
    sellPrice: 10000,
    stock: 20,
    minimumStock: 5,
    description: "Jus alpukat creamy dengan susu dan gula aren. Segar dan mengenyangkan.",
  },
  {
    id: "prd_jus_mangga",
    name: "Jus Mangga",
    category: "Jus Segar",
    buyPrice: 5000,
    sellPrice: 10000,
    stock: 20,
    minimumStock: 5,
    description: "Jus mangga segar, manis alami tanpa pewarna. Khas Nona Suka.",
  },
  {
    id: "prd_jus_jeruk",
    name: "Jus Jeruk",
    category: "Jus Segar",
    buyPrice: 4500,
    sellPrice: 8000,
    stock: 25,
    minimumStock: 5,
    description: "Jus jeruk peras segar, vitamin C tinggi. Favorit harian pelanggan.",
  },
  {
    id: "prd_jus_semangka",
    name: "Jus Semangka",
    category: "Jus Segar",
    buyPrice: 4000,
    sellPrice: 8000,
    stock: 18,
    minimumStock: 5,
    description: "Jus semangka dingin, menyegarkan di siang hari yang terik.",
  },
  {
    id: "prd_jus_wortel",
    name: "Jus Wortel Jeruk",
    category: "Jus Segar",
    buyPrice: 4500,
    sellPrice: 8000,
    stock: 15,
    minimumStock: 4,
    description: "Paduan wortel dan jeruk, kaya vitamin A dan C untuk imunitas.",
  },
  {
    id: "prd_jus_jambu",
    name: "Jus Jambu Biji",
    category: "Jus Segar",
    buyPrice: 4000,
    sellPrice: 8000,
    stock: 15,
    minimumStock: 4,
    description: "Jus jambu biji merah segar, kaya vitamin C dan antioksidan.",
  },

  // ── Frozen Food ──────────────────────────────────────────────
  {
    id: "prd_es_teh",
    name: "Es Teh Manis",
    category: "Frozen Food",
    buyPrice: 1500,
    sellPrice: 4000,
    stock: 50,
    minimumStock: 10,
    description: "Es teh manis segar, minuman andalan yang tidak pernah salah.",
  },
  {
    id: "prd_es_jeruk",
    name: "Es Jeruk",
    category: "Frozen Food",
    buyPrice: 2500,
    sellPrice: 5000,
    stock: 30,
    minimumStock: 8,
    description: "Es jeruk peras dingin, cocok menemani makan siang.",
  },
  {
    id: "prd_kopi_hitam",
    name: "Kopi Hitam",
    category: "Frozen Food",
    buyPrice: 1500,
    sellPrice: 4000,
    stock: 40,
    minimumStock: 10,
    description: "Kopi hitam robusta lokal, diseduh panas. Semangat pagi!",
  },
  {
    id: "prd_kopi_susu",
    name: "Kopi Susu Panas",
    category: "Frozen Food",
    buyPrice: 3000,
    sellPrice: 6000,
    stock: 30,
    minimumStock: 8,
    description: "Kopi susu panas dengan susu kental manis, manis dan creamy.",
  },
  {
    id: "prd_air_mineral",
    name: "Air Mineral 600ml",
    category: "Frozen Food",
    buyPrice: 2500,
    sellPrice: 4000,
    stock: 16,
    minimumStock: 10,
    description: "Air mineral dingin, tersedia di kulkas kasir.",
  },
  {
    id: "prd_teh_botol",
    name: "Teh Botol",
    category: "Frozen Food",
    buyPrice: 4200,
    sellPrice: 6000,
    stock: 20,
    minimumStock: 8,
    description: "Teh botol sosro, cocok ditaruh di rak depan kasir.",
  },

  // ── Sembako ───────────────────────────────────────────────────
  {
    id: "prd_beras_5kg",
    name: "Beras 5kg",
    category: "Sembako",
    buyPrice: 64500,
    sellPrice: 72000,
    stock: 7,
    minimumStock: 5,
    description: "Beras premium pulen, kebutuhan pokok keluarga.",
  },
  {
    id: "prd_gula_pasir",
    name: "Gula Pasir 1kg",
    category: "Sembako",
    buyPrice: 14500,
    sellPrice: 17000,
    stock: 11,
    minimumStock: 6,
    description: "Gula pasir putih, sering dibeli bersama kopi dan teh.",
  },
  {
    id: "prd_minyak_goreng",
    name: "Minyak Goreng 1L",
    category: "Sembako",
    buyPrice: 17000,
    sellPrice: 19500,
    stock: 6,
    minimumStock: 6,
    description: "Minyak goreng botol, putaran cepat perlu dipantau stoknya.",
  },

  // ── Kebutuhan Harian ─────────────────────────────────────────
  {
    id: "prd_sabun_cuci",
    name: "Sabun Cuci",
    category: "Kebutuhan Harian",
    buyPrice: 8500,
    sellPrice: 11000,
    stock: 18,
    minimumStock: 6,
    description: "Sabun cuci piring dan baju, repeat order stabil.",
  },
];

const transactions: Transaction[] = [
  {
    id: "trx_001",
    paymentMethod: "QRIS",
    total: 30000,
    createdAt: daysAgo(0, 8, 15),
    items: [
      { productId: "prd_nasi_goreng", productName: "Nasi Goreng Spesial", quantity: 1, unitPrice: 12000, costPrice: 7000 },
      { productId: "prd_jus_mangga", productName: "Jus Mangga", quantity: 1, unitPrice: 10000, costPrice: 5000 },
      { productId: "prd_es_teh", productName: "Es Teh Manis", quantity: 2, unitPrice: 4000, costPrice: 1500 },
    ],
  },
  {
    id: "trx_002",
    paymentMethod: "Tunai",
    total: 38000,
    createdAt: daysAgo(0, 11, 40),
    items: [
      { productId: "prd_nasi_ayam", productName: "Nasi Ayam Penyet", quantity: 2, unitPrice: 15000, costPrice: 9000 },
      { productId: "prd_es_jeruk", productName: "Es Jeruk", quantity: 1, unitPrice: 5000, costPrice: 2500 },
      { productId: "prd_kopi_hitam", productName: "Kopi Hitam", quantity: 1, unitPrice: 4000, costPrice: 1500 },
    ],
  },
  {
    id: "trx_003",
    paymentMethod: "Transfer",
    total: 46000,
    createdAt: daysAgo(1, 17, 5),
    items: [
      { productId: "prd_mie_goreng", productName: "Mie Goreng", quantity: 2, unitPrice: 10000, costPrice: 6000 },
      { productId: "prd_jus_alpukat", productName: "Jus Alpukat", quantity: 1, unitPrice: 10000, costPrice: 5500 },
      { productId: "prd_roti_bakar", productName: "Roti Bakar Coklat Keju", quantity: 2, unitPrice: 8000, costPrice: 5000 },
    ],
  },
  {
    id: "trx_004",
    paymentMethod: "Tunai",
    total: 27000,
    createdAt: daysAgo(2, 9, 25),
    items: [
      { productId: "prd_indomie", productName: "Indomie Goreng", quantity: 2, unitPrice: 6000, costPrice: 3500 },
      { productId: "prd_jus_jeruk", productName: "Jus Jeruk", quantity: 1, unitPrice: 8000, costPrice: 4500 },
      { productId: "prd_pisang_goreng", productName: "Pisang Goreng (3 pcs)", quantity: 1, unitPrice: 5000, costPrice: 3000 },
    ],
  },
  {
    id: "trx_005",
    paymentMethod: "QRIS",
    total: 32000,
    createdAt: daysAgo(5, 13, 10),
    items: [
      { productId: "prd_nasi_kuning", productName: "Nasi Kuning", quantity: 2, unitPrice: 8000, costPrice: 5000 },
      { productId: "prd_jus_semangka", productName: "Jus Semangka", quantity: 2, unitPrice: 8000, costPrice: 4000 },
    ],
  },
  {
    id: "trx_006",
    paymentMethod: "Tunai",
    total: 54000,
    createdAt: daysAgo(9, 10, 30),
    items: [
      { productId: "prd_nasi_goreng", productName: "Nasi Goreng Spesial", quantity: 2, unitPrice: 12000, costPrice: 7000 },
      { productId: "prd_jus_alpukat", productName: "Jus Alpukat", quantity: 2, unitPrice: 10000, costPrice: 5500 },
      { productId: "prd_gorengan", productName: "Gorengan Aneka (5 pcs)", quantity: 2, unitPrice: 5000, costPrice: 3000 },
    ],
  },
];

const debts: Debt[] = [
  {
    id: "debt_001",
    borrowerName: "Pak Darto",
    whatsapp: "081234567890",
    amount: 85000,
    createdAt: daysAgo(4, 9),
    dueDate: daysAgo(-1, 18),
    isPaid: false,
    lastReminderAt: daysAgo(1, 10, 30),
  },
  {
    id: "debt_002",
    borrowerName: "Bu Rini",
    whatsapp: "081298765432",
    amount: 42000,
    createdAt: daysAgo(2, 15, 10),
    dueDate: daysAgo(3, 18),
    isPaid: false,
  },
  {
    id: "debt_003",
    borrowerName: "Mas Ari",
    whatsapp: "081355599988",
    amount: 150000,
    createdAt: daysAgo(11, 8),
    dueDate: daysAgo(4, 18),
    isPaid: true,
    lastReminderAt: daysAgo(6, 8, 40),
  },
  {
    id: "debt_004",
    borrowerName: "Toko Sari",
    whatsapp: "081377744411",
    amount: 230000,
    createdAt: daysAgo(1, 12, 20),
    dueDate: daysAgo(-5, 16),
    isPaid: false,
  },
];

const expenses: Expense[] = [
  { id: "exp_001", title: "Belanja bahan jus pagi", amount: 85000, createdAt: daysAgo(0, 7, 10), category: "Belanja" },
  { id: "exp_002", title: "Gas LPG kompor", amount: 22000, createdAt: daysAgo(1, 9, 40), category: "Operasional" },
  { id: "exp_003", title: "Belanja ayam dan bumbu", amount: 95000, createdAt: daysAgo(2, 14, 10), category: "Belanja" },
  { id: "exp_004", title: "Bayar listrik kios", amount: 125000, createdAt: daysAgo(6, 11, 0), category: "Utilitas" },
  { id: "exp_005", title: "Restok buah-buahan", amount: 120000, createdAt: daysAgo(10, 8, 15), category: "Belanja" },
];

const settings: Settings = {
  storeName: "Kedai Nona Suka",
  storeTagline: "Makan enak, kantong aman",
  storeAddress: "Jl. Nona Suka No. 1, Makassar",
  ownerName: "Nona Suka",
  ownerWhatsapp: "081277788899",
  city: "Makassar",
  businessNotes: "Buka setiap hari 08:00–21:00 WITA. Fokus makanan, jus segar, dan minuman untuk pelanggan sekitar.",
  stockAlertThreshold: 5,
  enabledPayments: ["Tunai", "QRIS", "Transfer"],
};

export const seedState: AppState = {
  products,
  cart: [],
  transactions,
  debts,
  expenses,
  paymentMethod: "Tunai",
  settings,
};
